# Generated by Django 4.1.1 on 2022-10-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomados',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='num_tel_docente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='num_tel_estudiante',
            field=models.IntegerField(),
        ),
    ]
