# Generated by Django 4.1.1 on 2022-11-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0002_alter_diplomados_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomados',
            name='cursos_req',
        ),
        migrations.AddField(
            model_name='diplomados',
            name='cursos_req',
            field=models.ManyToManyField(to='artemis.cursos'),
        ),
    ]
