# Generated by Django 4.1.1 on 2022-11-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0004_inscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='nombre_inscripcion',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
