# Generated by Django 4.1.1 on 2022-11-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0005_inscripciones_nombre_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('fecha_exp', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.IntegerField()),
                ('numero_cuota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_inscripcion', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('num_cuotas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Inscripciones',
        ),
        migrations.AddField(
            model_name='matriculas',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artemis.periodo'),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='diplomado',
            field=models.ManyToManyField(to='artemis.diplomados'),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='estudiantes',
            field=models.ManyToManyField(to='artemis.estudiantes'),
        ),
        migrations.AddField(
            model_name='cuotas',
            name='cuotas_por_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artemis.matriculas'),
        ),
    ]
