# Generated by Django 4.1.1 on 2023-03-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0008_remove_matriculas_precio_diplomados_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='capacidad',
        ),
    ]
