# Generated by Django 4.1.1 on 2023-03-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0010_remove_matriculas_nombre_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='diplomado',
        ),
        migrations.AddField(
            model_name='matriculas',
            name='diplomado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artemis.diplomados'),
            preserve_default=False,
        ),
    ]
