# Generated by Django 4.1.7 on 2023-03-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0011_remove_matriculas_diplomado_matriculas_diplomado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artemis.becas'),
        ),
    ]
